/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package spotify.now.playing;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class SpotifyNowPlayingTest {
    @Test void appHasAGreeting() {
        SpotifyNowPlaying classUnderTest = new SpotifyNowPlaying();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
