/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package spotify.now.playing;

public class SpotifyNowPlaying {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new SpotifyNowPlaying().getGreeting());
    }
}
